### ISSUE TITLE
Benchmark on W4A16

### ISSUE THREAD

**Issue by RanchiZhao** [ruikangliu/FlatQuant#2]
Thank you for your work!
I wonder, are there any advantages to using FlatQuant in W4A16(perchannel+symmetric) compared to GPTQ(w. act_order)/AWQ, is FlatQuant still SOTA? For down_proj's quantization(I think the most hard one to quantize), any special?

**Comment by snowdusky** [comment]
Thank you for your interest in FlatQuant!

Compared to GPTQ and AWQ, FlatQuant achieves better accuracy but may experience less speedup in W4A16 (per-channel + symmetric) due to the transformations utilized to preprocess the weights before quantization, which introduce extra matrix multiplications. Detailed information on weight-only quantization accuracy can be found in our paper. However, just as we merge the transformation operator with activation quantization in weight-activation quantization, the transformation operator should also be able to merge with the dequantization operator in weight-only quantization to reduce extra overhead.

For down projection quantization, no specific strategies are needed to achieve SOTA performance, thanks to the flexibility of our fast and learnable transformations.

**Comment by RanchiZhao** [comment]
I read a [paper](https://arxiv.org/pdf/2406.01721), and I think your approach is to use gradient descent + Kronecker decomposition to replace their greedy solution for invertible matrices. Is this understanding correct?

**Comment by snowdusky** [comment]
Well, I think the difference mainly lies in three aspects: 
1. Global Transformation vs. Local Transformation: 
    As described in the paper, DuQuant employs a heuristic approach to construct a local orthogonal matrix of a small size, such as 128 and uses the same transformation matrix for different blocks within a single linear layer to avoid excessive overhead from pre-quantization transformations. While the local transformation is insufficient for effective outlier elimination, DuQuant introduces an additional reordering operator followed by another local transformation to incorporate global information. However, the combination of a global reordering operator and two local transformations is still limited compared to a global transformation. 
    In contrast, our method directly optimizes a global affine transformation, which has been shown to be more effective in eliminating outliers and reducing quantization error.

2. Orthogonal Transformation vs. Affine Transformation: 
    The permutation matrix constructed by DuQuant remains orthogonal, which keeps the final transformation matrix orthogonal. In contrast, our method utilizes affine transformations, which provide better flexibility and effectiveness in reducing quantization error.

3. Extra Overhead:  
    Our strategy of Kronecker decomposition and fusion kernel can greatly reduce the overhead from pre-quantization transformations without compromising the effectiveness of reducing quantization error, performing well in both efficiency and effectiveness.

**Comment by snowdusky** [comment]
The "global" and "local" I used primarily relative to the granularity of quantization. For example, when quantizing a single linear layer, both methods use a granularity of per-channel and per-token quantization (i.e., the input feature size, such as 4096). DuQuant utilizes a block-diagonal rotation matrix with identical blocks on the diagonal, reshaping the weights/activations to fit the size of the block rotation matrix (e.g., 128) before rotating them. While DuQuant adds a global reordering (where the reordering matrix size equals to the quantization granularity) to approximate a global transformation, the final transformation has been shown not to be optimal. In contrast, FlatQuant directly optimizes a global transformation (of size 4096). And I believe this is the critical difference between the two methods.

**Comment by RanchiZhao** [comment]
Thank you for your detailed response. In my various experimental setups, I found that FlatQuant is indeed a very effective method. I appreciate your work!
