### ISSUE TITLE
fake quantized model

### ISSUE THREAD

**Issue by mxjmtxrm** [ruikangliu/FlatQuant#6]
Hi, how to get a fake-quantized model?

**Comment by ruikangliu** [comment]
Hello, you can follow the "Calibration" section in README to get a fake-quantized model. To reproduce results in the paper, you can download pre-trained transformations from the modelzoo.

**Comment by cquxl** [comment]
How to save quanted model like Transformers' model, which can be directly used

**Comment by ruikangliu** [comment]
For weight and activation quantization, FlatQuant needs to insert some online transformations as well as activation quantization operations in the fake quantized model, so we suggest using our pre-defined model class for inference. More details can be found in `flatquant/model_tools`.
