### ISSUE TITLE
Some questions about reproducing SpinQuant PPL(5.9 in SpinQuant paper, 5.96 in your paper)

### ISSUE THREAD

**Issue by WeiMa01** [ruikangliu/FlatQuant#7]
Hello, everyone!
Thank you for the contributions to the quantization works!
I would like to discuss with you some issues regarding reproducing the results of the SpinQuant paper.
I use the code from [SpinQuant](https://github.com/facebookresearch/SpinQuant.git), and downlaod the trained R1, R2 from the following position: https://drive.google.com/drive/folders/1R2zix4qeXBjcmgnJN1rny93cguJ4rEE8?usp=sharing
When I inference the PPL of LLaMA-2-7B with the script 2_eval_ptq.sh(I use the defalut configuration w4A4KV4) and got the PPL 6.11, it is not equal to the PPL 5.9 or 5.96.
I changed the training paprameter(add activiation group size and weight block size to 128, modify the learning_rate from 1.5 to 0.001), got the trained R1 and R2.
I also changed the inference pareameter(add activiation group size and weight block size to 128), got the PPL 5.90. it seems the same with the SpinQuant paper, but the paper did not say they have used group size and block size, and the learning_rate is 1.5 in the paper.

This problem has confused me for several days. I would like to get your help. Could you share the training config(train R1 and R2) and inference config to reproduce SpinQuant PPL 5.9? thank you very much.

**Comment by WeiMa01** [comment]
I can reproduced the PPL 6.14 of SpinQuant.
Change the scripts/2_eval_ptq.sh file, from GPTQ quantization to RTN quantization（--w_rtn）

**Comment by ruikangliu** [comment]
To reproduce SpinQuant+GPTQ results, you should try the W16A4KV4 checkpoint instead of W4A4KV4 checkpoint. I think this may be the problem.

**Comment by WeiMa01** [comment]
Thank you very much for answer the question.
I run the default script(SpinQuant/scripts/2_eval_ptq.sh) with W16A4KV4 rotation matrix when inference, got the PPL 5.93x 
Thank you again for your help.
